server:
  port: 8086
keycloak:
  enabled: false
  configurationFile: ${KEYCLOAK_JSON_PATH:file:src/main/resources/keycloak.json}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5444/app}
    username: dev
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  mvc:
    pathmatch:
        matching-strategy: ANT_PATH_MATCHER
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

org:
  keycloak:
    url:
      base: ${KEYCLOAK_URL:http://localhost:8180}
      login: /realms/${REALM:kc-auth-realm}/protocol/openid-connect/token
    auth:
      user: ${KEYCLOAK_AUTH_USER:userservice}
      password: ${KEYCLOAK_AUTH_PASSWORD:123}
      client_id: ${KEYCLOAK_AUTH_CLIENT_ID:ks-auth-client}

